### PR TITLE
Model file valid before the first checkpoint.

### PR DESCRIPTION
**Pull request by tdomhan**
This resolves Issue https://github.com/awslabs/sockeye/issues/234. With the change the model folder is valid right from the start (as the params.best file will exist). This way one does no long get more not completely obvious error messages from sockeye.translate when trying to translate with a model that yet has to write the first checkpoint.

### CODE REVIEW

**Comment by chrkell** [comment]
I trained a model with Sockeye and my model directory is missing the params.best file. 

The error: sockeye.utils.SockeyeError: No model parameter file found under ../sockeye_training_output/params.best. This is either not a model directory or the first training checkpoint has not happened yet.

These were my parameters during training: 
```
params = {
        '--source': '../sentence_parallel_files/src_train.txt',
        '--target': '../sentence_parallel_files/tgt_train.txt',
        '--validation-source': '../sentence_parallel_files/src_validation.txt',
        '--validation-target': '../sentence_parallel_files/tgt_validation.txt',
        '--output': '../sockeye_training_output',
        '--shared-vocab': '',
        '--num-words': '20000',
        '--num-layers': '5:5',
        '--transformer-model-size': '512:512',
        '--transformer-attention-heads': '4:4',
        '--transformer-feed-forward-num-hidden': '2048:2048',
        '--embed-dropout': '0.3',
        '--label-smoothing': '0.3',
        '--optimized-metric': 'bleu',
        '--checkpoint-interval': '10',
        '--max-samples': '10000000'
    }
```

What do I do?

**Comment by mjdenkowski** [comment]
Can you share the contents of your model directory (`ls sockeye_training_output`) and the tail of the training log (`tail -n20 sockeye_training_output/log`)?

**Comment by chrkell** [comment]
Model directory:
Bildschirm­foto 2023-10-20 um 09 20 03

Tail of training log:
Bildschirm­foto 2023-10-20 um 09 39 50

**Comment by mjdenkowski** [comment]
It looks like training only ran for 1 checkpoint and may have ended with an error, although no error is reported. The model is early enough in training that we wouldn't expect it to produce any useful outputs.

At this point, there isn't much information available to diagnose potential issues. A first thing to try would be rerunning training with a smaller model to test the general setup. You could try `--transformer-model-size 128 --transformer-feed-forward-num-hidden 512 --num-layers 3:3`.

**Pull request merged**
