### PR TITLE
Make MxNet requirement >= rather than == since master is already mark…

### PR DESCRIPTION
**Pull request by mkolod**
Related Github issue: #447.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [x] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)
- [ ] You have considered writing a test
- [ ] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [ ] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by davvil** [comment]
This is dangerous as new releases of mxnet are not always backwards compatible. This is why we have the ==.

**Comment by tdomhan** [comment]
For now we always manually updated after manually verifying everything works when upgrading and I'd still lean towards continuing that practice. If someone wants to use a newer version of MXNet with Sockeye they can do so by passing the `--no-deps` flag to pip and make that conscious choice.

**Comment by fhieber** [comment]
Yes, lets stick with release version as dependencies

**Comment by mkolod** [comment]
Sounds good.

**Pull request closed without merging**
