### PR TITLE
More strict pep8 conformance

### PR DESCRIPTION
**Pull request by davvil**
Tested with flake8, maximum line length increased to 120

### CODE REVIEW

**Comment by davvil** [comment]
The CI tests fail because in rnn.py mypy needs the 'from typing import List', which is only used in mypy-oriented comments, thus flake8 complains about an unused import. Will try to make both happy.

**Comment by davvil** [comment]
It seems there is not a clean solution yet. https://gitlab.com/pycqa/flake8/issues/118

**Comment by fhieber** [comment]
Should we then leave it with mypy compatibility and not care too much about flake?

**Comment by davvil** [comment]
Says the one who always finds the missing two spaces before inline comments :-D

I tried with #noqa for flake8 and pylint: disable, but we cannot have both in one line AFAIK. Putting it in several lines is really ugly, so I removed them and put a comment about the import. That is the only complain by flake8 currently and mypy is happy again (CI tests).

**Pull request merged**
