### PR TITLE
Update to MXNet 1.2

### PR DESCRIPTION
**Pull request by fhieber**
**This PR updates Sockeye to MXNet 1.2 which was released May 21st 2018.**

Core change to Sockeye is the use of the new LayerNormalization operator which saves GPU memory. It uses the same set of parameters so I did not bump the major version.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [x] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)
- [x] You have considered writing a test
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fhieber** [comment]
@tdomhan @mjdenkowski @davvil @mjpost mxnet-1.2 is available and this can now be reviewed.

**Comment by davvil** [comment]
I don't know if we should bump up the major version, though. Users must update the mxnet version. It's "model backwards compatible" but not "system backwards compatible".

**Comment by fhieber** [comment]
Yeah, but if people can update their Sockeye code, they can also update mxnet (if sockeye is installed via pip, this is automatically happening).
The last time we updated mxnet (1.1) we also just did a minor version change.

**Comment by davvil** [comment]
Let's keep the major version, then.

**Pull request merged**
