### PR TITLE
Disabled dynamic batch sizing by default in Translator.translate due …

### PR DESCRIPTION
**Pull request by fhieber**
…to increased memory usage

Dynamic batching as introduced in #641 can lead to increased memory usage as MXNet doesn't seem to share memory well in this case. Until this is resolved, we disable dynamic batching by default and use padding as before.
Dynamic batching can still be turned on if the flag `fill_up_batches` is set to False in the `Translator.translate()` method.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [ ] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)
- [ ] You have considered writing a test
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tdomhan** [comment]
You mean it can be turned off when `fill_up_batches=False` in the comment above, right?

**Comment by fhieber** [comment]
Ah, yes `fill_up_batches=False` leads to dynamic batching.

**Comment by fhieber** [comment]
@tdomhan do you approve?

**Comment by sianvolta** [comment]
Checking in on dynamic batching again, is there still dynamic batching in sockeye2? Or at least something that matches https://github.com/marian-nmt/marian-dev `--mini-batch-fit ` option?

**Pull request merged**
