### PR TITLE
Sorting the sentences before batch decoding.

### PR DESCRIPTION
**Pull request by tdomhan**
- Sorting sentences before splitting them in batches.
 - Better default for the chunk size, which now depends on whether
 batching is enabled or not.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by mjpost** [comment]
Good call on the chunk size — I had fixed that myself on an internal branch. Have you run any tests to see if there is a speed improvement here?

**Comment by artemsok** [comment]
Looks good to me. One thing we might think of, after some benchmarking, is adapting the effective batch_size to the length distribution (treating the supplied one as an upper limit) to avoid fillers and for more uniform lengths inside a batch.

**Comment by fhieber** [comment]
@tdomhan is this ready to merge after rebasing on latest master?

**Comment by tdomhan** [comment]
Let's not merge yet. On some tests I observed different translations than the current master. I need to investigate what's going on.

**Comment by tdomhan** [comment]
ok, it's not really a bug. What happens (and also happened before the PR) is that the maximum output length is dependent on the bucket a sentence falls in, which in turn depends on the other sentences it gets grouped with. This leads to cases where sentences can potentially lead to a different translation with bucketing. This is only really the case when the maximum length was hit with a single sentence. 

I'd say we merge this PR as the behavior stays the same (just now sentences will be grouped differently). We can then separately discuss if we want to change this behavior.

**Comment by fhieber** [comment]
Thanks for the clarification, I will merge this then.

**Pull request merged**
