### PR TITLE
Avoid NDArray indexing in inference.

### PR DESCRIPTION
**Pull request by fhieber**
Surprisingly, allocating memory for `sequences`/`attentions` once in beam search and writing to index `t` seems to be slower than concatenating with every step.
Likewise, getting rid of the `pad_dist` write to `C.PAD_ID` index is faster.

This change gives about +1.5 sent/sec on a laptop/CPU with latest MXNet.
I have no access to a GPU right now, so no data on GPU performance. @tdomhan?

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [x] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mjpost** [comment]
I can test it.

**Comment by mjdenkowski** [comment]
Nice improvement!  Using 4 physical CPUs with mxnet-mkl, the translation speed goes up slightly as well with identical output.  Still need to test on GPUs, but looking good.

**Comment by mjpost** [comment]
This is just one run each, but the gains are pretty consistent:

```
Seconds / sentence (lower better). P2 (top) and P3 (bottom).
|          |      5 |     10 |     20 |
|----------+--------+--------+--------|
| baseline | 0.5681 | 0.6720 | 0.8557 |
| no_index | 0.5517 | 0.6382 | 0.8100 |
|----------+--------+--------+--------|
| baseline | 0.2828 | 0.3110 | 0.3730 |
| no_index | 0.2495 | 0.2884 | 0.3500 |
```

**Comment by fhieber** [comment]
this is additive to the improvements in the “blocks” and “gemm” branches which further improve things. 
Once this is merged, I will rebase those branches.

**Comment by mjpost** [comment]
I guess one thing we forgot on this was to bump the version and add a note.

**Pull request merged**
