### PR TITLE
Updating default parameters with values from our arXiv paper.

### PR DESCRIPTION
**Pull request by tdomhan**
(description of the change)

#### Pull Request Checklist ##
- [X] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [X] Unit tests pass (`pytest`)
- [X] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [X] System tests pass (`pytest test/system`)
- [X] Passed code style checking (`./style-check.sh`)
- [X] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [X] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tdomhan** [comment]
I've been meaning to do this for quite some time now. I think it's good to have the parameter values used in the arXiv paper as the default values to give a better out-of-the-box experience for users. I think it's fine to not bump the major version for this as models trained with the previous version can still be used at inference time.

**Comment by fhieber** [comment]
Agreed that it makes sense to update the default parameters to more recent best practices.
Does the default of `sockeye.train` still fit on a single commodity GPU device though? It might be useful to have a default configuration that is not only runnable on a huge cloud computing instance :)

Also, you might need to update the README.md and WMT/seqcopy tutorials with adjusted arguments

**Comment by tdomhan** [comment]
yeah, good points. I'll test the memory consumption and update the WMT tutorials next week.

**Comment by pengzhao-intel** [comment]
Does this default configuration coverage to the state-of-the-art in the paper?

**Comment by mjdenkowski** [comment]
For the WNMT18 baseline, we used a version of the arXiv settings adapted to use rate decay and early stopping vs a set number of steps: https://github.com/awslabs/sockeye/blob/wnmt18/wnmt18/train.sh.  These settings are also tailored to fit on a single GPU.

**Comment by tdomhan** [comment]
So the 6 layer Transformer seems to run fine on a p2 with the WMT tutorial training data. So I'd vote for having this as the default. What do you think?

**Comment by fhieber** [comment]
What about `--weight-tying --weight-tying-type=src_trg_softmax`?

**Comment by tdomhan** [comment]
to use weight tying in the tutorial?

**Comment by fhieber** [comment]
No, just asking because we refer to the new default settings as used in the arxiv paper, which had weight tying enabled.

**Comment by tdomhan** [comment]
oh ok, good point. The "problem" is that `--weight-tying` is a boolean parameter, so we would have to rename it to `--no-weight-tying`, enabling it by default, but being able to turn it off. I guess it could make sense to do that.

**Comment by tdomhan** [comment]
While in general having the Transformer and the learning parameters changed probably makes sense across language pairs and seq2seq problems, the same is probably not true for weight-tying, as we can't always share the source and target vocabs. Additionally, as one typically does not see a huge boost in BLEU from weight tying, but rather just needs to learn fewer parameters, I'd leave weight-tying as is by default (off), to cause fewer headaches when people use Sockeye for use cases where it does not apply.

**Comment by tdomhan** [comment]
makes sense, done!

**Pull request merged**
