### PR TITLE
Provide multiple source vocabularies as argument

### PR DESCRIPTION
**Pull request by franckbrl**
Following issue #527, `--source-vocab` can now take multiple files for additional source factor vocabularies.

We may want to consider changing a few variable/parameter names. For instance in `train.py`, now that `args.source_vocab` is a list, we may rename it to `args.source_vocabs` (parameter `--source-vocabs`), but it would probably not go well with the variable `source_vocabs` (produced by `create_data_iters_and_vocabs()`). This would also lead to a backwards-incompatible change.

Unit tests output 11 failures on the current master branch version. Since the content of this PR added no failures, I'm assuming the tests are passed.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [x] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)
- [ ] You have considered writing a test
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fhieber** [comment]
Thanks for adding this! Could you elaborate on what fails for you in unit tests? Current master runs tests just fine for me (and for Travis) so this must be something on your side.

Regarding the breaking change. If we would rename the `--source-vocab` argument for `sockeye.train` and `sockeye.prepare_data`, it would only affect training CLIs. While breaking any user scripts that call these, I would not view this as something that requires a major version bump. So i'd be fine with renaming these args and bumping only the minor version. Thoughts, @tdomhan ?

**Comment by franckbrl** [comment]
Ok, I'll change `--source-vocab` into `--source-vocabs` as soon as I get your confirmation.

The unit tests fails I get are all related to image captioning: see [unit_test.txt](https://github.com/awslabs/sockeye/files/2360231/unit_test.txt).

**Comment by fhieber** [comment]
Do you have python-pillow installed or something? Maybe its a version that is not compatible but it should skip these tests if not installed at all.
@lorisbaz can you advise?

**Comment by franckbrl** [comment]
I do have Pillow installed: 

```
>>> PIL.VERSION
'1.1.7'
```

**Comment by lorisbaz** [comment]
It seems that the problem is:`TypeError: integer argument expected, got float`.
It might be related to the PIL version. I tested it with `5.2.0`.

**Comment by mjpost** [comment]
Note that there is a hidden backward-incompatibility in the 1.18 range with the `lhuc` parameter (if you trained a model with 1.18.early, it won't run with 1.18.now). It's an easy fix (just add the keyword to the config file) but technically should have required a version bump. So together with this, it might be a reason to bump the major version.

**Comment by franckbrl** [comment]
Thanks @lorisbaz, upgrading Pillow to version `5.2.0` removed a few failures, but I still get 6: [unit_test.txt](https://github.com/awslabs/sockeye/files/2361078/unit_test.txt).

```
>>> PIL.__version__
'5.2.0'
```

**Comment by lorisbaz** [comment]
It seems related to multiple sources, since image captioning supports only a single-source input encoders.

**Comment by fhieber** [comment]
@lorisbaz but that doesn't explain the failure of the tests, or does it? On Travis, are these tests being run? I think they are because travis installs the dev requirements, including Pillow.

**Comment by franckbrl** [comment]
I get the same 6 failures on the master branch version. There's certainly an issue with my environment.

**Comment by fhieber** [comment]
Seems like it. Could you rebase onto latest master?

**Comment by franckbrl** [comment]
Sure, so we stay on a minor change? If so, should I increment the Sockeye version to `1.18.54`, or just add a line in `CHANGELOG.md` under version `1.18.53`? Otherwise, we switch to version `1.19.0`.

**Comment by tdomhan** [comment]
I'm not sure this warrants a major version change, as there is no backwards compatibility in the sense that a trained model won't work at inference time anymore. The fact that LHUC apparently introduced a non backwards-compatible changes means that we should fix that separately (namely, being robust against `lhuc` missing).

**Comment by franckbrl** [comment]
The code is rebased on the latest master branch. We now have version `1.18.54`.

Are there any further thoughts on changing `--source-vocab` to `--source-vocabs`?

**Comment by mjpost** [comment]
To keep this backwards compatible, why not add `--source-vocabs` but keep `--source-vocab` (that takes just one argument). Then, when 1.19 comes out, you could remove the latter.

I agree about not incrementing for this relatively small change, but it seems like bad form to actually break everyone's scripts without incrementing.

**Comment by franckbrl** [comment]
I like the idea, although it would require two distinct ways of importing the vocabularies, according to whether `--source-vocab` is set or not. And we would probably need to raise an error when `source_vocabs[0] != source_vocab` and both are set.

Another solution would be to leave `--source-vocab` and create `--source-factor-vocabs` specifically for source factor vocabularies (not tokens). This would be consistent with the way source token and factor data files are provided (`--source` and `--source-factors`). And this would be fully backwards compatible.

**Comment by mjpost** [comment]
The sanity check don't seem like that much of a burden. But I do also like the `--source-factor-vocabs` approach for 1.18, then removing it in 1.19 in favor of `--source-factors`. But this will all be up to the Amazon folks.

**Comment by tdomhan** [comment]
Either of those two solutions sound good. Not breaking people's training scripts is definitely something we should try to do, unless it's unavoidable.

The solution with `--source-factor-vocabs` might be a bit cleaner. Then we could open a issue for version 1.19 in order to not forget reconsidering using a single `--source-vocabs` argument.

**Comment by franckbrl** [comment]
`--source-vocab` remains unchanged and `--source-factor-vocabs` was just added.

**Comment by fhieber** [comment]
yes, thanks for the change!

**Pull request merged**
