### PR TITLE
Standardizing to batch major data.

### PR DESCRIPTION
**Pull request by tdomhan**
(description of the change)

#### Pull Request Checklist ##
- [X] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [X] Unit tests pass (`pytest`)
- [ ] System tests pass (`pytest test/system`)
- [X] Passed code style checking (`./pre-commit.sh` or manual run of pylint & mypy)
- [X] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [X] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tdomhan** [comment]
the system tests are currently running and I will do some further testing before merging.

**Comment by fhieber** [comment]
seems like travis is still failing due to code checking (missing `-> None` for `__init__()`)

**Comment by tdomhan** [comment]
I anyway want to do some more testing before merging ;)

**Comment by tdomhan** [comment]
alright, we figured out the MXNet but and this change would be ready to be merged after approval.

**Pull request merged**
