### PR TITLE
Update to MXNet 1.8 & Python 3.7

### PR DESCRIPTION
**Pull request by fhieber**
updates to mxnet 1.8 and Python 3.7.

MXNet 1.8 in pypi no longer publishes wheels for mac Python 3.6, we therefore bump our minimum python version from 3.6 to 3.7.

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [ ] System tests pass (`pytest test/system`)
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by tdomhan — APPROVED** [review]

**Comment by tdomhan** [comment]
Huh, that's actually surprising that Python 3.6 was removed. Is there a way to allow a different set of Python versions for Linux? EOL for Python 3.6 is end of this year and I believe it is still widely used. So if possible I think we should keep 3.6 support till then.

**Comment by tdomhan** [comment]
I guess the publishing version isn't important necessarily, but it currently uses `3.6`: https://github.com/awslabs/sockeye/blob/master/.github/workflows/python-publish.yml#L20

**Comment by fhieber** [comment]
We depend on mxnet and if mxnet decides to drop 3.6 support we are kind of forced to go along.
Good catch, we should update the publish workflow as well.

**Comment by tdomhan** [comment]
yeah, absolutely. I meant that MXNet dropping 3.6 is something Mac OS specific so that we could still support Linux + 3.6.

**Comment by fhieber** [comment]
We need to find out then how to encode that in the Github actions file (not sure how to do this).

**Pull request merged**
