### PR TITLE
Preventing accidental use of setuptools install.

### PR DESCRIPTION
**Pull request by tdomhan**

### CODE REVIEW

**Comment by fhieber** [comment]
Related note: should we do a `pip install .` in the travis build?

**Comment by tdomhan** [comment]
we don't install sockeye in travis, no?

**Comment by tdomhan** [comment]
let's actually hold off from merging. I want to run some more tests with this to make sure we don't block anything.

**Comment by tdomhan** [comment]
`bdist_wheel` actually runs `install`.... so maybe it's not a good idea to forcefully forbid using `setup.py install`...

**Comment by fhieber** [comment]
Makes sense.
Regarding travis: no we dont install but we could as an additional test maybe.

**Comment by tdomhan** [comment]
will discard for now...

**Pull request closed without merging**
