### PR TITLE
Transformer optimization: cache linear input projections of source data (keys & values) of source attention layers

### PR DESCRIPTION
**Pull request by fhieber**
This change adds caching of linear projections of the memory data (the source representation) of the source-attention layers in TransformerDecoderBlocks. 
Specifically, the FullyConnected operations to obtain the keys & values for source-attention are now computed by the encoder module during inference and hence only once. The result is then fed as input to the inference decoder module using the general state interface of decoders.
This should be orthogonal to the changes in the blocks/gemm branches and/or symbolic beam search. It simply avoids repetitive computation.

In my preliminary tests this gave a speedup of about +1 sent/sec on my laptop with small models on CPU. 
As I don't have access to a GPU right now, @mjpost would you be so kind to benchmark on a GPU, again with varying batch/beam sizes?
Thanks!

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
- [x] System tests pass (`pytest test/system`)
- [x] Passed code style checking (`./style-check.sh`)
- [ ] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [ ] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fhieber** [comment]
rebased onto latest master

**Comment by fhieber** [comment]
I ran a contrastive benchmark using a representative transformer model on a P3 instance using a rather small input corpus (n=500). Bottom line: caching this doesn't help with small beam sizes, the workload of the linear projections is just too small to be a bottleneck for the P3. For larger batch sizes however, a small improvement can be observed:

| beam_size 1    | sec/sent  |
| ------------- |:-------------:|
| master        | 0.2533 |
| this PR       | 0.2707 | 

| beam_size 8   | sec/sent  |
| ------------- |:-------------:|
| master        | 0.0760 |
| this PR       | 0.0747 | 

| beam_size 16    | sec/sent  |
| ------------- |:-------------:|
| master        |  0.0544 |
| this PR       | 0.0521 | 

| beam_size 32    | sec/sent  |
| ------------- |:-------------:|
| master        | 0.0430 |
| this PR       | 0.0411 | 

On the CPU a speed up even for batch size 1 can be observed. I'd be curious to see how it behaves on a p2.
Could anyone run this branch on a p2?

**Comment by mjpost** [comment]
Hi Felix — sorry I haven't been able to get to this. I am testing this now. Any suggestions for the parameter sweep? I'll do (batch: 1 10 20) x (beam: 1 5 10 20 30) x (arch: p2 p3) by default.

**Comment by fhieber** [comment]
That sounds great, thanks! There is no rush with this PR. Its something I wanted to do for a while but not too important anyway.

**Comment by mjpost** [comment]
Here are the raw results:

```
run,arch,beam,batch,total_time
baseline,p2,1,1,1207.8867
contrastive,p2,1,1,1358.2168
baseline,p2,1,10,241.3485
contrastive,p2,1,10,229.9562
baseline,p2,1,20,162.8698
contrastive,p2,1,20,147.8890
baseline,p2,5,1,1654.9278
contrastive,p2,5,1,1650.2668
baseline,p2,5,10,464.5439
contrastive,p2,5,10,384.6898
baseline,p2,5,20,423.8038
contrastive,p2,5,20,356.8233
baseline,p2,10,1,2037.6015
contrastive,p2,10,1,1852.3979
baseline,p2,10,10,811.2956
contrastive,p2,10,10,681.7946
baseline,p2,10,20,780.5154
contrastive,p2,10,20,656.1216
baseline,p2,20,1,2508.0065
contrastive,p2,20,1,2205.1205
baseline,p2,20,10,1532.1789
contrastive,p2,20,10,1237.4897
baseline,p2,20,20,1458.5026
contrastive,p2,20,20,1218.0806
baseline,p2,30,1,2994.5541
contrastive,p2,30,1,2539.2747
baseline,p2,30,10,2047.5170
contrastive,p2,30,10,1737.0206
baseline,p2,30,20,2110.9933
contrastive,p2,30,20
baseline,p3,1,1,716.1371
contrastive,p3,1,1,784.7877
baseline,p3,1,10,112.2021
contrastive,p3,1,10,117.3727
baseline,p3,1,20,81.7385
contrastive,p3,1,20,78.4114
baseline,p3,5,1,769.8671
contrastive,p3,5,1,910.2761
baseline,p3,5,10,172.8370
contrastive,p3,5,10,170.3431
baseline,p3,5,20,118.9938
contrastive,p3,5,20,110.4213
baseline,p3,10,1,879.8313
contrastive,p3,10,1,936.1999
baseline,p3,10,10,211.8205
contrastive,p3,10,10,200.2875
baseline,p3,10,20,169.8434
contrastive,p3,10,20,154.5614
baseline,p3,20,1,1062.2044
contrastive,p3,20,1,1073.8633
baseline,p3,20,10,312.0452
contrastive,p3,20,10,281.1415
baseline,p3,20,20,287.7864
contrastive,p3,20,20,253.4007
baseline,p3,30,1,1144.2602
contrastive,p3,30,1,1146.7389
baseline,p3,30,10,419.9707
contrastive,p3,30,10,370.0666
baseline,p3,30,20,397.9044
contrastive,p3,30,20,352.6325
```

**Comment by fhieber** [comment]
seems in line with my p3 results: this only helps with large workloads (i.e. large batch and/or beam sizes). 
I'd vote for not merging this for now but keeping the branch. We may want to revisit this feature with symbolic/fully unrolled beam search.

Any other opinions? @tdomhan?

**Comment by tdomhan** [comment]
not merging for now and revisiting after other inference changes in the future sounds reasonable.

**Comment by tdomhan** [comment]
should we close the PR and keep the branch?

**Comment by fhieber** [comment]
Makes sense. I'd vote for keeping the PR open to not forget about this branch.

**Comment by fhieber** [comment]
This is already part of the `sockeye_2` branch, closing.

**Pull request closed without merging**
