### PR TITLE
fix warmup of learning rate so that it works properly w/ continued tr…

### PR DESCRIPTION
**Pull request by tuglat**
…aining

(description of the change)

#### Pull Request Checklist ##
- [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [x] Unit tests pass (`pytest`)
  There were failures, but they are the same failures exhibited by the master branch
- [no] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [x] System tests pass (`pytest test/system`)
  There were failures, but they are the same failures exhibited by the master branch
- [x] Passed code style checking (`./style-check.sh`)
- [no] You have considered writing a test
- [x] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by fhieber — APPROVED** [review]
Again, thanks for contribution!

**Comment by fhieber** [comment]
Would it be possible to add a unit test?

**Comment by tuglat** [comment]
I'm not sure what to put in a unit test, the problem seems to lie more in the way pieces interact. 

I guess I could create a training instance, manipulate the counters, and force it to save state. Then create new training instance, load state, and check to make sure that various instance variable are what i expect.

**Comment by fhieber** [comment]
Yes, you are right, it's a bit of a hassle. It'd be good to have but if you think it is too much work, let me know, we can merge then.

**Comment by tuglat** [comment]
Let's just merge as is.

**Pull request merged**
