### PR TITLE
Warn when waiting for checkpoint decoder.

### PR DESCRIPTION
**Pull request by tdomhan**
- Warn when waiting for the checkpoint decoder.
 - Removed functionality to have multiple concurrent decoder, as this
 can in the worst case lead to the training being interrupted, as each
 decoder potentially delays has_improved, which in combination with slow
 decoders leads to the early stopping criterion kicking in. With this
 change the delay is at most one.

#### Pull Request Checklist ##
- [X] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [X] Unit tests pass (`pytest`)
- [X] Passed code style checking (`./pre-commit.sh` or manual run of pylint & mypy)
- [X] You have considered writing a test
- [X] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [X] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tdomhan** [comment]
yeah, this only is an issue when using the BLEU score. The main point was to add the logging when we wait. As we anyway don't use the other feature and there's a potential issue with when we optimize for BLEU, I remove it in the same commit.

**Comment by fhieber** [comment]
Sounds good!

**Comment by fhieber** [comment]
@tdomhan I will merge after rebase

**Comment by fhieber** [comment]
The travis fail seems to be unrelated: fail of pylint due to matplotlib import error. I will merge this.

**Pull request merged**
