### PR TITLE
translator: send skip_nvs and nvs_thresh from args to ctor

### PR DESCRIPTION
**Pull request by graehl**
### Fixed

- Send skip_nvs and nvs_thresh args to Translator constructor in sockeye-translate instead of ignoring them.

### Added

- log beam search avg output vocab size

---

#### Pull Request Checklist
 * [x] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
 * [x] Unit tests pass (pytest)
 * [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
 * [x] System tests pass (pytest test/system)
 * [x] Passed code style checking (./style-check.sh)
 * [x] You have considered writing a test
 * [x] Updated major/minor version in sockeye/__init__.py. Major version bump if this is a backwards incompatible change.
 * [x] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mjdenkowski** [comment]
Hi Jonathan,

Thanks for your interest in contributing to Sockeye!

It looks like you're working on a few different changes in your branch. When you're ready to share any of them, you can create a new branch for the specific change and open a pull request, which will bring up a template to describe the contribution.

Best,
Michael

**Comment by graehl** [comment]
The topic is Neural Vocabulary Selection. First commit fixes a bug: documented option to turn off NVS (or change threshold) doesn't do anything. The second commit just logs the average vocabulary size.
Are you suggesting a separate branch+pull request for each? If so, no problem.
Is there interest in both parts or just the bugfix?

**Comment by graehl** [comment]
I saw a checklist template and complied. Are you saying that you want me to keep the template and put [ x ] in the [ ]?

**Comment by fhieber** [comment]
Hi Johnathan,

Leaving everything in 1 PR is fine but please leave in the checklist and the statement that you release your changes under Apache 2.0 license. 
Thanks!

**Comment by graehl** [comment]
Thanks, Felix. See new desc above.

**Review by fhieber — APPROVED** [review]
Thanks for the fix and refactor!

**Pull request merged**
